# Generated by Django 3.2.6 on 2021-08-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='isEmergency',
        ),
    ]
