# Generated by Django 3.2.6 on 2021-08-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210822_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-time',)},
        ),
    ]
