# Generated by Django 3.2.6 on 2021-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(default='New Jersey', max_length=128),
            preserve_default=False,
        ),
    ]
